[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'justmao945/vim-clang'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'vim-scripts/SingleCompile'

[[plugins]]
repo = 'vim-scripts/taglist.vim'

[[plugins]]
repo = 'jceb/vim-hier'

[[plugins]]
repo = 'wesleyche/SrcExpl'

[[plugins]]
repo = 'wesleyche/Trinity'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'scrooloose/nerdtree'
